//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled 구인구직프로젝트
//  @ File Name : Person.java
//  @ Date : 2016-09-12
//  @ Author :  정미애
//
//




public class Person {
	private String name;
	public String birth;
	protected String tel;
	      char gender;
	public String addr;

	public String showInfo() {
	 String info="이름: "+name+"\n생년월일: "+birth;
	        info+="\n연락처: "+tel+"\n성별:"gender;
	        info+="\n주소: "+addr;
			return info;
	}
	public void wantJob(String type, int pay) {
		System.out.println(name+"님의 희망 직업: "+type);
		System.out.println(name+"님의 희망 연봉: "+pay"만원");


	}
}
