/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc_memo;

import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
//날짜 포맷
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MemoGUI extends javax.swing.JFrame {

    public MemoGUI() {
        initComponents();
        //추가 로직
        //lbWdate에 오늘 날짜 동적으로 설정하기
        Date today=new Date();
        SimpleDateFormat df=new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String str=df.format(today);
        lbWdate.setText(str);
        //오라클 : yyyy-mm-dd hh:mi:ss
        //자바   : yyyy-MM-dd hh:mm:ss
        taList.setEditable(false);
        taList.setFont(new Font("serif",Font.PLAIN,22));
        
        //table에 마우스이벤트 처리=> Anonymous class로 처리하자.
        table.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mousePressed(MouseEvent e) {
        		//setTitle("##");
        		//1. 마우스로 누른 지점의 글번호를 알아내자.
        		int row=table.getSelectedRow();
        		int col=table.getSelectedColumn();
        		//setTitle("row: "+row+", col: "+col);
        		
        		//선택한 글 번호 가져오기
        		Object objIdx=table.getValueAt(row, 0);
        		Integer idx=(Integer)objIdx;
        		
        		//2. 사용자에게 해당 글을 삭제할 것인지 확인
        		int yn=JOptionPane.showConfirmDialog(table, 
        				idx+"번 글을 삭제할까요?");
        		//setTitle("yn: "+yn);
        		//3. 삭제하겠다고 하면 dao 의 deleteMemo(글번호) 호출
        		if(yn==JOptionPane.YES_OPTION) {
        			int r=dao.deleteMemo(idx);
        			String str=(r>0)?"삭제 성공":"삭제 실패";
        			showMessage(str);
        			find();
        		}
        	}
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tfName = new javax.swing.JTextField();
        lbIdx = new javax.swing.JLabel();
        lbWdate = new javax.swing.JLabel();
        tfMsg = new javax.swing.JTextField();
        btWrite = new javax.swing.JButton();
        btList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taList = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        combo = new javax.swing.JComboBox<>();
        tfSearch = new javax.swing.JTextField();
        btFind = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("::한줄 메모장 v1.1::");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 153), 3, true));

        tfName.setBorder(javax.swing.BorderFactory.createTitledBorder("::작성자::"));

        lbIdx.setText("글번호:  ");

        lbWdate.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbWdate.setForeground(new java.awt.Color(102, 0, 102));
        lbWdate.setText("작성일: 2019-11-26");

        tfMsg.setBorder(javax.swing.BorderFactory.createTitledBorder("::메모 내용::"));
        

        btWrite.setBackground(new java.awt.Color(0, 102, 153));
        btWrite.setForeground(new java.awt.Color(255, 255, 255));
        btWrite.setMnemonic('I');
        btWrite.setText("글쓰기");
        btWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btWriteActionPerformed(evt);
            }
        });

        btList.setBackground(new java.awt.Color(204, 0, 204));
        btList.setForeground(new java.awt.Color(255, 255, 255));
        btList.setMnemonic('L');
        btList.setText("글목록");
        btList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMsg)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbIdx, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lbWdate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(btWrite)
                        .addGap(18, 18, 18)
                        .addComponent(btList, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btList, btWrite});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btList, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btWrite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(tfMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lbWdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lbIdx))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btList, btWrite});

        jScrollPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(":::메모 목록:::"), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        taList.setColumns(20);
        taList.setRows(5);
        jScrollPane1.setViewportView(taList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("한줄 메모장", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "작성자", "메모내용", "작성일" }));

        btFind.setText("검   색");
        btFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btFind)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btFind, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder("::검색 결과::"), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4)));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "글번호", "작성자", "메모내용", "작성일"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setFocusCycleRoot(true);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("메모 검색", jPanel2);

        jLabel1.setFont(new java.awt.Font("한컴 솔잎 B", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("::한줄 메모장:::");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/memo01.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>  
    MemoDAO dao=new MemoDAO();
    private void btWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btWriteActionPerformed
    		//1) tfName, tfMsg값 얻어오기
    		String name=tfName.getText();
    		String msg=tfMsg.getText();
    	
    		//2) 유효성 체크(사용자가 값을 입력 안했을 경우)
    		if(name==null||msg==null||name.trim().contentEquals("")
    				||msg.trim().isEmpty()) {
    			//null값과 빈문자열 체크
    			showMessage("모든 값을 입력하세요");
    			tfName.requestFocus();//입력 포커스 주기
    			return;
    		}
    	
    		//3) 1)얻은 값으로  MemoVO 객체를 생성해서  setting하기
    		MemoVO memo=new MemoVO(0,name,msg,null);
    	
    		//4) MemoDAO객체 생성후 insertMemo()호출하기
    		int cnt=dao.insertMemo(memo);
    		String str=(cnt>0)?"메모 등록 성공":"메모 등록 실패";
    		//5) 그 실행 결과에 따라 다이얼로그박스 보여주기
            showMessage(str);
            tfName.setText("");
            tfMsg.setText("");
            tfName.requestFocus();
            
            showList();//글목록 가져와 보여주기
    }//----------------------------------------
    
    public void showMessage(String str) {
    	JOptionPane.showMessageDialog(this, str);
    }
    private void btListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListActionPerformed
    	showList();
    }//---------------------------------
    
    public void find() {
    	//1. 검색유형 알아내기(combo)
    	int n=combo.getSelectedIndex();
    	setTitle("n: "+n);
    	//2. 검색어 얻어오기
    	String keyword=tfSearch.getText();
    	
    	//3. 유효성 체크 (검색어 입력 안했을 경우)
    	if(keyword==null||keyword.trim().isEmpty()) {
    		//showMessage("검색어를 입력하세요");
    		//검색어를 입력하지 않으면 모든 글 가져오기
    		ArrayList<MemoVO> arr2=dao.listMemo();
    		showTable(arr2);
    		tfSearch.requestFocus();
    		return;
    	}
    	//4. dao.findMemo(검색유형, 검색어);==>반환값 받아서 (데이터)
    	ArrayList<MemoVO> arr=dao.findMemo(n, keyword);    	
    	showTable(arr);
    }
    
    private void btFindActionPerformed(java.awt.event.ActionEvent evt) {
    	find();
   } //---------------------------------
    String[] colHeader= {"글번호","작성자","메모내용","작성일"};
    public void showTable(ArrayList<MemoVO> arr) {
    	//DefaultTableModel model=new DefaultTableModel(2차원배열,1차원배열)
    	Object[][]data=new Object[arr.size()][4];
    	//ArrayList에 있는 내용을 data에 옮기기
    	for(int i=0;i<data.length;i++) {
    		MemoVO memo=arr.get(i);
    		data[i][0]=memo.getIdx();
    		data[i][1]=memo.getName();
    		data[i][2]=memo.getMsg();
    		data[i][3]=memo.getWdate();
    	}
    	DefaultTableModel model=new DefaultTableModel(data,colHeader);
    	table.setModel(model);
    }//---------------------------------
    
    public void showList() {
    	ArrayList<MemoVO> arr=dao.listMemo();
    	showTaList(arr);
    }//---------------------------------
    
    public void showTaList(ArrayList<MemoVO> arr) {
    	if(arr==null) {
    		showMessage("SQL오류");
    		return;
    	}
    	if(arr.size()==0) {
    		taList.setText("데이터가 없습니다");
    	}else {
    		taList.setText("");
    		taList.append("=============================================\n");
    		taList.append("글번호\t작성자\t작성일\t메모내용\n");
    		taList.append("=============================================\n");
    		for(MemoVO m:arr) {
    			taList.append(m.getIdx()+"\t"+m.getName()+"\t"+m.getWdate());
    			taList.append("\t"+m.getMsg()+"\n");
    		}
    		taList.append("=============================================\n");
    	}
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
Metal
Nimbus
CDE/Motif
Windows
Windows Classic 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            	System.out.println(info.getName());
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemoGUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify                     
    private javax.swing.JButton btFind;
    private javax.swing.JButton btList;
    private javax.swing.JButton btWrite;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbIdx;
    private javax.swing.JLabel lbWdate;
    private javax.swing.JTextArea taList;
    private javax.swing.JTable table;
    private javax.swing.JTextField tfMsg;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration          
}
